import 'bootstrap/dist/css/bootstrap.css'
import '../styles/globals.css'
import type {AppProps} from 'next/app'
import Head from "next/head";


function MyApp({Component, pageProps}: AppProps) {
  return <>
    <Head>
      <title>Proyecto Migala Jalisco</title>

      <meta name='description' content='Generated by create next app'/>
      <meta name="viewport" content="width=device-width, initial-scale=1"/>

    </Head>
    <Component {...pageProps} />
  </>
}

export default MyApp
