import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Start from './Start'
//El componente start es el que tiene el primer layout de la landing
const Home: NextPage = () => {
  return (
   <>
   <Head>
    <title>Proyecto Migala Jalisco</title>
    <meta name='description' content='Generated by create next app'/>
   </Head>
    <Start/>
   </>
  
    )
}

export default Home
